CREATE OR REPLACE TABLE `rakamin-kf-analytics-508414.kimia_farma.kf_analisa` AS

SELECT
  * EXCEPT(provinsi),

  CASE
    WHEN UPPER(TRIM(provinsi)) IN ('ACEH', 'NANGGROE ACEH DARUSSALAM') THEN 'ID-AC'
    WHEN UPPER(TRIM(provinsi)) = 'SUMATERA UTARA' THEN 'ID-SU'
    WHEN UPPER(TRIM(provinsi)) = 'SUMATERA BARAT' THEN 'ID-SB'
    WHEN UPPER(TRIM(provinsi)) = 'RIAU' THEN 'ID-RI'
    WHEN UPPER(TRIM(provinsi)) = 'JAMBI' THEN 'ID-JA'
    WHEN UPPER(TRIM(provinsi)) = 'SUMATERA SELATAN' THEN 'ID-SS'
    WHEN UPPER(TRIM(provinsi)) = 'BENGKULU' THEN 'ID-BE'
    WHEN UPPER(TRIM(provinsi)) = 'LAMPUNG' THEN 'ID-LA'
    WHEN UPPER(TRIM(provinsi)) IN ('KEPULAUAN BANGKA BELITUNG', 'BANGKA BELITUNG') THEN 'ID-BB'
    WHEN UPPER(TRIM(provinsi)) IN ('KEPULAUAN RIAU', 'RIAU KEPULAUAN') THEN 'ID-KR'

    WHEN UPPER(TRIM(provinsi)) IN ('DKI JAKARTA', 'JAKARTA') THEN 'ID-JK'
    WHEN UPPER(TRIM(provinsi)) = 'JAWA BARAT' THEN 'ID-JB'
    WHEN UPPER(TRIM(provinsi)) = 'JAWA TENGAH' THEN 'ID-JT'
    WHEN UPPER(TRIM(provinsi)) IN ('DI YOGYAKARTA', 'YOGYAKARTA') THEN 'ID-YO'
    WHEN UPPER(TRIM(provinsi)) = 'JAWA TIMUR' THEN 'ID-JI'
    WHEN UPPER(TRIM(provinsi)) = 'BANTEN' THEN 'ID-BT'

    WHEN UPPER(TRIM(provinsi)) = 'BALI' THEN 'ID-BA'
    WHEN UPPER(TRIM(provinsi)) = 'NUSA TENGGARA BARAT' THEN 'ID-NB'
    WHEN UPPER(TRIM(provinsi)) = 'NUSA TENGGARA TIMUR' THEN 'ID-NT'

    WHEN UPPER(TRIM(provinsi)) = 'KALIMANTAN BARAT' THEN 'ID-KB'
    WHEN UPPER(TRIM(provinsi)) = 'KALIMANTAN TENGAH' THEN 'ID-KT'
    WHEN UPPER(TRIM(provinsi)) = 'KALIMANTAN SELATAN' THEN 'ID-KS'
    WHEN UPPER(TRIM(provinsi)) = 'KALIMANTAN TIMUR' THEN 'ID-KI'
    WHEN UPPER(TRIM(provinsi)) = 'KALIMANTAN UTARA' THEN 'ID-KU'

    WHEN UPPER(TRIM(provinsi)) = 'SULAWESI UTARA' THEN 'ID-SA'
    WHEN UPPER(TRIM(provinsi)) = 'SULAWESI TENGAH' THEN 'ID-ST'
    WHEN UPPER(TRIM(provinsi)) = 'SULAWESI SELATAN' THEN 'ID-SN'
    WHEN UPPER(TRIM(provinsi)) = 'SULAWESI TENGGARA' THEN 'ID-SG'
    WHEN UPPER(TRIM(provinsi)) = 'GORONTALO' THEN 'ID-GO'
    WHEN UPPER(TRIM(provinsi)) = 'SULAWESI BARAT' THEN 'ID-SR'

    WHEN UPPER(TRIM(provinsi)) = 'MALUKU' THEN 'ID-MA'
    WHEN UPPER(TRIM(provinsi)) = 'MALUKU UTARA' THEN 'ID-MU'

    WHEN UPPER(TRIM(provinsi)) = 'PAPUA' THEN 'ID-PA'
    WHEN UPPER(TRIM(provinsi)) = 'PAPUA BARAT' THEN 'ID-PB'
    WHEN UPPER(TRIM(provinsi)) = 'PAPUA TENGAH' THEN 'ID-PT'
    WHEN UPPER(TRIM(provinsi)) = 'PAPUA PEGUNUNGAN' THEN 'ID-PP'
    WHEN UPPER(TRIM(provinsi)) = 'PAPUA SELATAN' THEN 'ID-PS'
    WHEN UPPER(TRIM(provinsi)) = 'PAPUA BARAT DAYA' THEN 'ID-PD'

    ELSE NULL
  END AS kode_provinsi,

  provinsi

FROM `rakamin-kf-analytics-508414.kimia_farma.kf_analisa`;